/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 8fb954eb813ea35b566c8cef82d32d35)
declare namespace Cloudflare {
	interface Env {
		CHAT_AGENT_PATH: string;
		CHAT_AGENT_NAME: string;
		CHAT: DurableObjectNamespace<import("./src/server").Chat>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CHAT_AGENT_PATH" | "CHAT_AGENT_NAME">> {}
}
