/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: e9ef331d581cf27a7c3887f1566b7650)
declare namespace Cloudflare {
	interface Env {
		CHAT_AGENT_PATH: string;
		CHAT_AGENT_NAME: string;
		CHAT_AGENT: DurableObjectNamespace<import("./src/worker").Chat>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CHAT_AGENT_PATH" | "CHAT_AGENT_NAME">> {}
}
